# Generated by Django 4.2.7 on 2024-01-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user_created',
            field=models.ForeignKey(default='dcd9c03f-23e3-4e34-b116-647df3978f70', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
