# Generated by Django 5.0.1 on 2024-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
